### ISSUE TITLE
Great example! But... what if someone changes language while a validation message is already showing.

### ISSUE THREAD

**Issue by SanderCokart** [gcascio/next-intl-zod#2] opened 2024-10-25 14:10 UTC
What if someone changes language while a validation message is already showing.
Right now when switching locale the old language shows because the t() is called before render rather than in the rendered component so no revalidation/rerender of the message

**Comment by gcascio** [comment] 2024-10-28 11:55
Hi, thanks for your feedback I appreciate it! I can't reproduce the behaviour you describe in this example. Since a locale change is triggered by a navigation the page gets re-rendered which resets the client state:
 
https://github.com/user-attachments/assets/266359fd-495e-489b-9d25-c734b12e0b44

**Comment by SanderCokart** [comment] 2024-10-28 12:07
Yeah this happens in the context of no i18n routing. So its not triggered
by a route change

**Comment by gcascio** [comment] 2024-10-28 13:19
I see, this is a bit out of the scope of the example but in that case you would have to set the zod error map for the new locale which could be done with a modification of `useI18nZodErrors`:

```ts
export const useI18nZodErrors = (locale: string) => {
  const t = useTranslations('zod');
  const tForm = useTranslations('form');
  const tCustom = useTranslations('customErrors');

  useEffect(() => {
    z.setErrorMap(makeZodI18nMap({ t, tForm, tCustom }));
  }, [locale, t, tForm, tCustom]);
};
```

and in the form you need to revalidate all error fields, i.e. in the form component

```ts
useEffect(() => {
  const errorKeys = Object.keys(errors).map((key) => key) as Array<keyof Schema>;
  trigger(errorKeys)
}, [trigger, locale, errors]);
```

I hope this gives a general idea on how to approach it!

**Comment by gcascio** [comment] 2024-11-04 19:39
I'm going to close this issue with the example provided. If any other issues come up, feel free to reach out!

**Closed as completed by gcascio** 2024-11-04 19:39 UTC
